name: cudaCubeML
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - tqdm
  - h5py
  - jupyter
  - pydocstyle
  - pylint
  - flake8
  - matplotlib
  - git
  - pip
  - pandas
  - scikit-learn=0.22
  - pytorch>=1.3.0
  - torchvision
  - cudatoolkit=10.1
  - ignite=0.2.1
  - numpy
  - pillow
  - pip:
    - wandb
