name: cudaCubeML
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _pytorch_select=0.2=gpu_0
  - astroid=2.4.1=py37hc8dfbb8_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - curl=7.69.1=h33f0ec9_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - flake8=3.8.2=pyh9f0ad1d_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - git=2.26.2=pl526h5e3e691_0
  - glib=2.64.3=h6f030ca_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - h5py=2.10.0=nompi_py37h513d04c_102
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - ignite=0.2.1=py37_0
  - importlib-metadata=1.6.0=py37hc8dfbb8_0
  - importlib_metadata=1.6.0=0
  - ipykernel=5.3.0=py37h43977f1_0
  - ipython=7.15.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37hc8dfbb8_1
  - jedi=0.17.0=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.15.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - kiwisolver=1.2.0=py37h99015e2_0
  - krb5=1.17.1=h2fd8d38_0
  - lazy-object-proxy=1.4.3=py37h8f50634_2
  - ld_impl_linux-64=2.34=h53a641e_4
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.69.1=hf7181ac_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libiconv=1.15=h516909a_1006
  - liblapack=3.8.0=14_mkl
  - libllvm9=9.0.1=he513fc3_1
  - libpng=1.6.37=hed695b0_1
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.9.0=hab1572f_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_1
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37h30547a4_0
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h8f50634_1001
  - mkl=2019.5=281
  - mkl-service=2.3.0=py37h516909a_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.10.0=hc9558a2_0
  - notebook=6.0.3=py37hc8dfbb8_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.4=py37h8960a57_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.4=py37h0da4684_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.1.2=py37h718be6c_0
  - pip=20.1.1=py_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.20=py_0
  - pydocstyle=5.0.2=py_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.6.1=py_0
  - pylint=2.5.2=py37hc8dfbb8_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyrsistent=0.16.0=py37h8f50634_0
  - python=3.7.6=h8356626_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=cuda101py37h02f0884_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pyzmq=19.0.1=py37hac76be4_0
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.7.4=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - readline=8.0=hf8c457e_0
  - scikit-learn=0.22.2.post1=py37hcdab131_0
  - scipy=1.4.1=py37ha3d9a3c_3
  - send2trash=1.5.0=py_0
  - setuptools=47.1.1=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.0.0=py_0
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - torchvision=0.2.1=py37_0
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.46.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - typed-ast=1.4.1=py37h516909a_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h8f50634_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - chardet==3.0.4
    - click==7.1.2
    - configparser==5.0.0
    - docker-pycreds==0.4.0
    - gitdb==4.0.5
    - gitpython==3.1.2
    - gql==0.2.0
    - graphql-core==1.1
    - idna==2.9
    - nvidia-ml-py3==7.352.0
    - pathtools==0.1.2
    - promise==2.3
    - psutil==5.7.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pyyaml==5.3.1
    - requests==2.23.0
    - sentry-sdk==0.14.4
    - shortuuid==1.0.1
    - smmap==3.0.4
    - subprocess32==3.5.4
    - urllib3==1.25.9
    - wandb==0.8.36
    - watchdog==0.10.2
prefix: /home/bjoernhm/miniconda3/envs/cudaCubeML

