name: cubeml
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - tqdm
  - h5py
  - jupyter
  - pydocstyle
  - pylint
  - flake8
  - matplotlib
  - git
  - pip
  - scikit-learn
  - pytorch
  - torchvision
  - cpuonly
  - ignite
  - numpy
  - pillow
  - pip:
    - wandb
