name: powershovel
channels:
  - anaconda
dependencies:
  - pylint
  - pydocstyle
  - flake8
  - pandas
  - pytables
  - plotly
  - numpy
  - scipy
  - scikit-learn
  - pathlib
  - dvc[azure]
  - pip
  - pip:
    - streamlit
